= FAQ

== Super-fast commit

Fim is able to commit using the super-fast mode (or fast mode). In that case, it checks into the repository for modifications using the selected mode. +
And then it do a full hash of the modified files in order to fill up the missing hash. +
*Using Super-fast commit allow to save a lot of time.* With this option you can miss some modified files.

This means that even if the global hash mode of your repository is hash all, you can commit using either fast mode or super-fast mode.

Super-fast commit example:

[source, bash]
------
$ fim init -y -c "Create the repository slowly in full mode"
Info  - Scanning recursively local files, using 'full' mode and 2 threads
...

# Do some modifications

$ fim ci -s -y -c "Commit modifications very quickly using super-fast commit"
Info  - Scanning recursively local files, using 'super-fast' mode and 2 threads
...
Info  - Retrieving the missing hash for all the modified files, using 'full' mode and 2 threads
...

# Do some modifications

$ fim ci -f -y -c "Commit modifications quickly using fast commit"
Info  - Scanning recursively local files, using 'fast' mode and 2 threads
...
Info  - Retrieving the missing hash for all the modified files, using 'full' mode and 2 threads
...
------

== Run Fim commands from a sub-directory

You can run all the Fim commands from every sub-directory inside a Fim repository.
You can see it in action into the <<simple-example.adoc#_from_the_code_dir01_code_sub_directory,Simple example>>.

Doing this allow you to:

- Quickly find the modifications done in this specific sub-directory. You will hash only the files contained inside and not the complete file tree
- Quickly commit the modifications done in this sub-directory
- Quickly find the duplicated files contained in this sub-directory
- Quickly reset the attributes of files contained in this sub-directory

All the other commands will run as if you were on the top of the Fim repository.

== Changing default hash mode

If you never want to hash the complete content of your files you can set a global hash mode that will indicate the maximum hash mode you want to use for this repository.
You can specify this to the init command:

- `-f`: Sets maximum hash mode to fast. You will be able to use `-f`, `-s` or `-n` after
- `-s`: Sets maximum hash mode to super-fast. You will be able to use `-s` or `-n` after
- `-n`: Means always don't hash anything. You won't be able to use other hash mode after

=== Example

Initialize the Fim repository specifying the global hash mode.

[source, bash]
----
$ fim init -f
----

It sets a global hash mode for the complete repository to fast mode. +
All the Fim commands that you use after will use by default the fast hash mode (or less if specified) and you won't be able to hash the full file contents.

After the init command that we run in our example, you will be able to run the following commands:

[source, bash]
----
$ fim diff    # will run using -f

$ fim diff -s

$ fim diff -n
----

== Ignoring files or directories

You can specify files or directories that you want to be ignored by Fim.
For this, you can add a `.fimignore` file in one of the directories contained into the Fim repository. +
You can also set global ignores by creating a `.fimignore` into the user home directory.

Each line of the `.fimignore` file specifies a pattern. The pattern is mainly a file or directory name. +
Use wildcards in order to match many of them. For example `\*.mp3` will match all the files ending with `.mp3`. +
A leading `*\*` followed by a slash means match in all directories. +
For example, `**/foo` matches a file or a directory named `foo` anywhere, starting from where the `.fimignore` contain this pattern.

== Hash files in multi-thread

Fim hashes files using several threads.
This allows taking advantage of the computer resources and maximizes the overall performances of file hashing. +
By default, Fim use an arbitrary thread count that is the number of CPU core divided by two. +
You can specify, using the `-t` option, the number of thread to be used for file hashing. +
The best value depends on the kind of hard disk you have. The more throughputs you have, the more thread you can use.

== State integrity

Every State file contains a hash of the State content. +
If something is modified in the State file, the hash of the State content will change and the State will be reported as corrupted. +
Fim won't use a corrupted State.

== Cross platform compatibility

The same Fim repository can be used by either on Linux, Mac OS X and Windows. +
State content is normalized and the same State content can be loaded on the different supported OS.
