= FAQ

== Run Fim commands from a sub-directory

You can run all the Fim commands from every directory inside the Fim repository.
It allows you to:

- Quickly find the modifications done in this directory. You will hash only the files contained inside and not the complete file tree
- Quickly commit the modifications done in this directory
- Quickly find the duplicated files contained in this directory
- Quickly reset the date of files contained in this directory

All the other commands will run as if you were on the top of the repository.

== Dealing with duplicates

Duplicated files are addressed by Fim in two different ways.

=== Duplicates inside a Fim repository

Fim allow you to detect duplicates using the `fdup` command.
If you want to remove them, Fim cannot do it. It does not provide a smart way to remove those duplicates.

=== Duplicates that are outside

You can use Fim to remove duplicated files that are located outside a Fim repository using the `rdup` command.
It can be useful if you want to cleanup old backups that are no more synchronized and you want to be sure to not loose any files that could have been modified or added.

== Changing default hash mode

If you never want to hash the complete content of your files you can set a global hash mode that will indicate the maximum hash mode you want to use for this repository.
You can specify this to the init command:

- `-f`: means always don't hash anything
- `-k`: You will be able to use `-f` or `-k` after
- `-m`: You will be able to use `-f`, `-k` or `-m` after

Example:
`shell
~/sample$ fim init -m
`

It sets a global hash mode for the complete repository to `-m`.
All the Fim commands that you use after will use `-m` hash mode (or less if specified) and you won't be able to hash the full file content.
After you will be able to run the following commands:

[source,shell]
----
~/sample$ fim diff # will run using -m

~/sample$ fim diff -k

~/sample$ fim diff -f
----

== Ignoring files or directories

You can specify files or directories that you want to be ignored by Fim.
For this, you can add a `.fimignore` file in one of the directories contained into the Fim repository.
You can also set global ignores by creating a `.fimignore` into the user home directory.

Each line of the `.fimignore` file specifies a pattern. The pattern is mainly a file or directory name.
Use wilcards in order to match many of them. For example `*.mp3` will match all the file ending with `.mp3`.
A leading `**` followed by a slash means match in all directories.
For example, `**/foo` matches file or directory `foo` anywhere, the same as pattern `foo`.

== Hash files in multi-thread

Fim hash files using several threads.
This allow taking advantage of the computer resources and maximize the overall performances of file hashing.
By default, Fim use an arbitrary thread count that is the number of CPU cores divided by two.
You can specify the number of thread to be used for file hashing.
The best value depend on the kind of hard disk you have. The more throughput you have, the more thread you can use.

== State integrity

All the States contains a hash of the State content.
If something is modified in the State, the hash of the State content will change and the State will be reported as corrupted.
Fim won't use it.

== Cross Platform Compatibility

The same Fim repository can be used by either on Linux and on Windows.
State content is normalized and the same State content can be loaded either on Linux and Windows.