= File permissions management

Checking the integrity of data files can be good, but we need also to ensure that file permissions are not compromised.

Fim is able to save and restore back file permissions. +
To do so it stores for each file:

* The https://en.wikipedia.org/wiki/Discretionary_access_control[DAC] information:
** On Linux and Mac OS X file permission like `rwxrwxrwx` is stored.
** On Windows the Archive, Hidden, ReadOnly and System attributes are stored.

* The https://en.wikipedia.org/wiki/Mandatory_access_control[MAC] information: +
Currently the *SELinux label* is stored, if supported by the OS.

You can check file permissions using the `diff` command. A quick result can be produced using the do not hash mode (`-n` option),
but in this case Fim will not be able to detect file permissions change for files that have been renamed. +
If some permission has changed and you want to restore them use the `rfa` command.

When you use the same Fim repository with different OS, file permissions that are not supported are ignored.