= Fim workflow


First you need to initialize the Fim repository using the `init` command.
This will record the first State of your file tree.

[source, bash]
----
$ fim init
----

After having done modifications into the file tree, you can compare get the status that will show the differences between the recorded State and
the current file tree using the `status` command. You can do a full status check that will compare the hash of all the files.
It can be slow as all the file contents will be read and hashed.

[source, bash]
----
$ fim st
----

You can compare quickly using the fast mode. *With this option you can miss some modified files.*

[source, bash]
----
$ fim st -f
----

You can compare quicker using the super-fast mode. *With this option you can miss some modified files.*

[source, bash]
----
$ fim st -s
----

Otherwise, you can request to not hash file content using the `-n` option. It will compare only the file names, file length, modification dates and permissions.
You will not be able to detect files that have been renamed or duplicated.

[source, bash]
----
$ fim st -n
----

Each time you want to record the State of the current file tree you can use the `commit` command. +
It's a time consuming operation that will compute hash of every file contents.

[source, bash]
----
$ fim ci -c "My commit comment"
----

In order to commit faster you can use the Super-fast commit. More details in <<super_fast_commit.adoc#_super_fast_commit,Super-fast commit>>. (with this option you can miss some modified files)

[source, bash]
----
$ fim ci -s -c "My commit comment"
----
