= Fim workflow


First you need to initialize the Fim repository using the `init` command.
This will record the first State of your file tree.

[source,shell]
----
$ fim init
----

Then you can compare the differences between the recorded State and the current file tree using the diff command.
You can do a full diff that will compare the hash of all the files. It can be very slow as all the files content will be read.

[source,shell]
----
$ fim diff
----

You can compare quickly asking to hash only the second 1 MB block of the files. *Using this option can produce an inaccurate result.*

[source,shell]
----
$ fim diff -m
----

You can compare quicker asking to hash only the second 4 KB block of the files. *Using this option can produce an inaccurate result.*

[source,shell]
----
$ fim diff -k
----

Otherwise, you can request to not hash file content using the fast mode (-f option). It will compare only the file names and modification dates.
You will not be able to detect files that have been renamed or duplicated.

[source,shell]
----
$ fim diff -f
----

Each time you want to record the State of the current file tree you can use the commit command.
It's a time consuming operation that will compute all the hash of each files content.

[source,shell]
----
$ fim ci
----