= How does it work

Fim creates an index of the files that are managed. It contains for each
file:

* file name & length
* file attributes (dates, permissions)
* hash of 3 small blocks
* hash of 3 medium blocks
* hash of the full file content

For the 3 blocks hash it is one at the beginning, one in the middle and one at the end. +
The block that is hash at the beginning is not the first one. Most of the files contains headers, so to produce accurate hash
of small of medium blocs we skip the first block and hash the second one,
but when the file size is less than twice the block size we hash the first block.

The small block size is 4 KB and the medium block size is 1 MB. +
The hash algorithm that is used is SHA-512.

More details regarding file permissions can be found <<file-permissions-management.adoc#_file_permissions_management,here>>.

The index is called a `State` and acts like the Central Directory does for a Zip file.
All the data generated by Fim is stored into the `.fim` root directory.

Fim keeps each version of the different State that have been committed. +
You cannot use them to retrieve the content of one file that you may have lost.

NOTE: *Fim does not replace a backup software*
