= How does it work

Fim creates an index of the files that are managed. It contains for each
file:

* File name & length
* File attributes (dates, permissions)
* Hash of 3 small blocks
* Hash of 3 medium blocks
* Hash of the full file content

The 3 blocks that are hashed are one at the beginning, one in the middle and one at the end. +
The block that is hashed at the beginning is not the first one. Most of the files contain headers, so to produce accurate hash
we skip the first block and hash the second one.
When the file size is less than twice the block size we hash the first block.

The small block size is 4 KB and the medium block size is 1 MB. +
The hash algorithm that is used is SHA-512.

More details regarding file permissions can be found <<file-permissions-management.adoc#_file_permissions_management,here>>.

The index is called a `State` and acts like the Central Directory does for a Zip file.
All the data generated by Fim are stored into the `.fim` located into the root directory of the Fim repository.

Fim keeps each version of the different State that has been committed. +
But you cannot use them to retrieve the content of one file that you may have lost.

NOTE: *Fim does not replace a backup software*
