= Most Common use cases

Fim can be used for different kind of use cases.

== Binary Workspace management
Personally I use Fim to manage my photos and videos.
When I have new photos, I put them at the right place in my pictures folder and then I do `fim&nbsp;ci` from the sub-directory
containing the new photos to record a new State, as I could do with Git.
As I do this from a sub-directory the commit is fast because Fim hashes only the files that I added and creates a new State
by merging those new hashes with the previous State.

More details on using Fim from a sub-directory can be found in <<faq.adoc#_run_fim_commands_from_a_sub_directory,Run Fim commands from a sub-directory>>.

The `fim diff` command let me know when I want (even super quickly) if something changed in my pictures folder.

== Duplicates removal
I can easily identify and delete the photos I have duplicated on my drive or another computer with the command `fim rdup`. +
For this, I just need to copy the `.fim` directory on the other computer. +
More details in <<faq.adoc#_dealing_with_duplicates,Dealing with duplicates>>.

== Backup integrity
For offline long term backups Fim can be used to perform and store a hash of all the files in order to insure the backup integrity. +
More details in <<why-do-you-need-fim.adoc#_why_do_you_need_fim,Why do you need Fim>>
and <<hardware-corruption-detection.adoc#_hardware_corruption_detection,Hardware corruption detection>>.
