= Real life example

== Initialize the big Fim repository

Here is the output of the initialization of a big Fim repository that contains 297 GB of photos and videos. +
In my case *it takes almost 3 hours* to hash all the files content.

[source,shell]
----
photos-videos$ fim init -y
No comment provided. You are going to initialize your repository using the default comment.
2015/10/22 19:23:05 - Info  - Scanning recursively local files, using 'full' mode and 2 threads
(Hash progress legend for files grouped 10 by 10: # > 1 GB, @ > 200 MB, O > 100 MB, 8 > 50 MB, o > 20 MB, . otherwise)
2015/10/22 19:23:06 - Info  - SELinux is enabled on this system
.................................................................o.o...o......8........O.........oo.
...O....................#.................Oooooooooooo.@.o.o.oo..oo@................o.......88oOoooo
... # Hash progress legend shortened
.................................o.............@ooooo@oooooooooooooooooo.ooooooooooooooooooooooooooo
..............................................
2015/10/22 22:05:50 - Info  - Scanned 41467 files (297 GB), hashed 297 GB (avg 31 MB/s), during 02:42:44

... # File list is skipped as it is too long

41467 added
----

== Check very quickly for differences

It is possible to check the differences very quickly using the `-s` option that will check only 3 small blocks of 4 KB. +
In my case *it takes 17 minutes :=)*.

[source,shell]
----
photos-videos$ fim diff -s
2015/10/22 23:15:52 - Info  - Scanning recursively local files, using 'super fast' mode and 2 threads
(Hash progress legend for files grouped 10 by 10: # > 1 GB, @ > 200 MB, O > 100 MB, 8 > 50 MB, o > 20 MB, . otherwise)
2015/10/22 23:15:52 - Info  - SELinux is enabled on this system
.................................................................o.o...o......8........O.........oo.
...O....................#.................Oooooooooooo.@.o.o.oo..oo@................o.......88oOoooo
... # Hash progress legend shortened
.................................o.............@ooooo@oooooooooooooooooo.ooooooooooooooooooooooooooo
..............................................
2015/10/22 23:32:57 - Info  - Scanned 41467 files (297 GB), hashed 484 MB (avg 484 KB/s), during 00:17:04

Comparing with the last committed state from 2015/10/22 19:23:06
Comment: Initial State

Nothing modified
----

== Check more accurately for differences

Using the super fast mode can produce inaccurate results. *You can miss some modified files.* +
To increase accuracy, you can use the fast mode using the `-f` option that will check 3 medium blocks. +
Even if, using this mode increase accuracy, it cannot be completely accurate as we only hash 3 different 1 MB blocks of the files. +
This time in my case, *it takes 42 minutes* to check the differences.

[source,shell]
----
photos-videos$ fim diff -f
2015/10/22 23:33:22 - Info  - Scanning recursively local files, using 'fast' mode and 2 threads
(Hash progress legend for files grouped 10 by 10: # > 1 GB, @ > 200 MB, O > 100 MB, 8 > 50 MB, o > 20 MB, . otherwise)
2015/10/22 23:33:23 - Info  - SELinux is enabled on this system
.................................................................o.o...o......8........O.........oo.
...O....................#.................Oooooooooooo.@.o.o.oo..oo@................o.......88oOoooo
... # Hash progress legend shortened
.................................o.............@ooooo@oooooooooooooooooo.ooooooooooooooooooooooooooo
..............................................
2015/10/23 00:15:05 - Info  - Scanned 41467 files (297 GB), hashed 51 GB (avg 21 MB/s), during 00:41:42

Comparing with the last committed state from 2015/10/22 19:23:06
Comment: Initial State

Nothing modified
----

== Fully checking for differences

If you want to be completely sure of the `diff` result, you need to run a full hash of all the files content using the `diff` command without any option. +
This time in my case, *it takes almost 3 hours* as for the `init` command.

== Checking without hashing

There is also the do not hash mode using the `-n` option that will not hash the files content.
It helps to detect faster changes but you will be able to detect only file names and file attributes that have changed. +
This time in my case, *it takes 46 seconds*.

[source,shell]
----
photos-videos$ fim diff -n
2015/10/22 23:14:53 - Info  - Not hashing file content so thread count forced to 1
2015/10/22 23:14:53 - Info  - Scanning recursively local files, using 'do not hash' mode and 1 thread
2015/10/22 23:14:54 - Info  - SELinux is enabled on this system
2015/10/22 23:15:40 - Info  - Scanned 41467 files (297 GB), during 00:00:46

Comparing with the last committed state from 2015/10/22 19:23:06
Comment: Initial State

Nothing modified
----