#!/bin/sh
#-----------------------------------------------------------------------------------------------------------------------
# This file is part of Fim - File Integrity Manager
#
# Copyright (C) 2025 Etienne Vrignaud
#
# Fim is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Fim is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fim.  If not, see <https://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------------------------------------------------

docker build -t evrignaud/fim .

#-----------------------------------------------------------------------------------------------------------------------
# Then you need (as explained here https://docs.docker.com/linux/step_five) to:
# - Tag the image with the current Fim version
#    $ docker tag 8cad533f4601 evrignaud/fim:1.2.2
# - Upload it in Docker Hub
#    $ docker login
#    $ docker push evrignaud/fim
# - Send refresh to microbadger
#    $ curl -X POST https://hooks.microbadger.com/images/evrignaud/fim/jY5c5byoJJ6XZSKajrIQ0Zz13Kk=
#-----------------------------------------------------------------------------------------------------------------------
