#!/bin/bash
#-----------------------------------------------------------------------------------------------------------------------
# File Integrity Manager (FIM).
# ______ _ _         _____      _                  _ _           ___  ___
# |  ___(_) |       |_   _|    | |                (_) |          |  \/  |
# | |_   _| | ___     | | _ __ | |_ ___  __ _ _ __ _| |_ _   _   | .  . | __ _ _ __   __ _  __ _  ___ _ __
# |  _| | | |/ _ \    | || '_ \| __/ _ \/ _` | '__| | __| | | |  | |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|
# | |   | | |  __/   _| || | | | ||  __/ (_| | |  | | |_| |_| |  | |  | | (_| | | | | (_| | (_| |  __/ |
# \_|   |_|_|\___|   \___/_| |_|\__\___|\__, |_|  |_|\__|\__, |  \_|  |_/\__,_|_| |_|\__,_|\__, |\___|_|
#                                        __/ |            __/ |                             __/ |
#                                       |___/            |___/                             |___/
#
# FIM manage the integrity of a complete file tree.
# With FIM you can manage the integrity of a big amount of data files that you could not put into an archive.
# For example videos and photos can be managed by this tool.
# Using it you can ensure the integrity of a whole videos / photos directory tree.
# To do so FIM manages States that acts like the Central Directory does for a Zip file.
# One State is an index that holds one entry per file that contains the file name,
# a hash of the file content and the file modification date.
# Only the States are kept into an history. There is no history for the file content.
# This tool is an unversioned control system (uvcs).
#
# Created by evrignaud on 05/05/15.
#-----------------------------------------------------------------------------------------------------------------------

currentDir=`pwd`

baseDir=`dirname "$(readlink -f "$0")"`

mkdir -p ${baseDir}/classes

libraries=${baseDir}/lib/gson-2.3.1.jar:${baseDir}/lib/commons-cli-1.2.jar

javac -cp ${libraries} -d ${baseDir}/classes `find ${baseDir}/src -name "*.java"`

java -cp ${baseDir}/classes:${libraries} org.fim.Main "${1}" "${2}" "${3}" "${4}" "${5}" "${6}"
