#!/bin/bash
#-----------------------------------------------------------------------------------------------------------------------
# This file is part of Fim - File Integrity Manager
#
# Copyright (C) 2016  Etienne Vrignaud
#
# Fim is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Fim is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Fim.  If not, see <http://www.gnu.org/licenses/>.
#-----------------------------------------------------------------------------------------------------------------------

CURRENT_DIRECTORY="$PWD"
REPOSITORY_ROOT="$CURRENT_DIRECTORY"
while [ "$REPOSITORY_ROOT" != "/" ];
do
    REPOSITORY_ROOT="$(realpath -s "$REPOSITORY_ROOT"/..)"
    if [ -d "$REPOSITORY_ROOT/.fim" ];
    then
        break;
    fi
done

SUBDIR="$(echo "$CURRENT_DIRECTORY" | sed -e "s|$REPOSITORY_ROOT/||")"

(
    cd "$REPOSITORY_ROOT"
    docker run -it --rm=true -u $(id -u):$(id -g) -v $PWD:/working_directory --name=fim-$(date +%N) fim:latest fim $* -d "$SUBDIR"
)

#-----------------------------------------------------------------------------------------------------------------------
